
# 🎲 Reproducibility
seed: 42

# Paths (relative to project root)
paths:
  raw: "data/raw/swiggy.csv"
  interim: "data/interim"
  

# Restaurant cleaning parameters
restaurants:
  price:
    min: 50.0
    max: 3000.0
  
  delivery_fee:
    base_min: 20.0
    base_max: 40.0
    variation: 10.0
  
  # India geographic bounds (for validation)
  bounds:
    lat_min: 8.0
    lat_max: 37.0
    lon_min: 68.0
    lon_max: 97.0
  
  # Location jitter in degrees (±3.3km at equator)
  location_jitter: 0.06
  
  # Export filenames
  output_name: "restaurants_clean"

# User generation parameters
users:
  total: 50000
  max_fav_cuisines: 5
  output_name: "users"

# Weather & Traffic Data Generation
days: 7  # Start with 1 week, not 30
#max_routes_per_city: 50  # Temporarily reduce further
chunk_hours: 24

# Weather Configuration
weather:
  city_baselines:  # Average annual temperature per city
    bangalore: 26
    mumbai: 29
    delhi: 24
    hyderabad: 28
    pune: 24
    kolkata: 28
    chennai: 30
    ahmedabad: 27
    surat: 28

# Traffic Configuration
traffic:
  city_baselines:  # Base congestion level per city (0.0-1.0)
    bangalore: 0.7
    mumbai: 0.7
    delhi: 0.65
    hyderabad: 0.55
    pune: 0.5
    kolkata: 0.6
    chennai: 0.55
    ahmedabad: 0.4
    surat: 0.4
  
  noise_std: 0.08  # Random noise standard deviation for traffic
